# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  buildwin: 
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [ windows-latest ] 
    steps:
    - uses: actions/checkout@v2 
    - name: Install and Pack 
      run: |
        npm install
        npm run build-w-64
        npm run build-w-arm64
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: outs
        path: |
          out/*exe # window 安装包

  buildmac: 
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [ macOS-latest ] 
    steps:
    - uses: actions/checkout@v2 
    - name: Install and Pack 
      run: |
        npm install
        npm run build-m
        npm run build-m-arm64
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: outs
        path: |
          out/*dmg # mac 安装包

  builddebian: 
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [ ubuntu-latest ] 
    steps:
    - uses: actions/checkout@v2 
    - name: Install and Pack 
      run: |
        npm install
        npm run build-l-64
        npm run build-l-arm64
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: outs
        path: |
          out/*deb # debian 安装包

  buildcentos: 
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [ centos-latest ] 
    steps:
    - uses: actions/checkout@v2 
    - name: Install and Pack 
      run: |
        npm install
        npm run build-lr-64
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: outs
        path: |
          out/*rpm # redhat 安装包